# Cron job to run the run-deposit-stage command
name: make run-deposit-stage
on:
  schedule:
    - cron:  "0 12 * * *" #times are in UTC, so this is 7am et
jobs:
  deploy:
    name: Run a deposit command
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.WILEY_DEPLOY_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.WILEY_DEPLOY_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: run command to do deposits in stage
        run: make run-deposit-stage
